version: "2"

services:
  node:
    image: "node:8"
    # user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - "8081"
    ports:
      - "8081:8081"
    command: "npm start"